/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto.gui.telas;

import java.util.ArrayList;
import java.util.List;
import javax.swing.ListSelectionModel;
import projeto.erro.ConexaoException;
import projeto.erro.DaoException;
import projeto.erro.RegraExceptionTratamento;
import projeto.negocio.classesBasicas.Tratamento;
import projeto.negocio.fachada.FachadaTratamento;
import projeto.util.Msg;
import projeto.util.TableTratamento;

/**
 *
 * @author Mario
 */
public class TelaConsultaTratamento extends javax.swing.JFrame {

    /**
     * Creates new form TelaConsultaTratamento
     */
    public TelaConsultaTratamento() {
        initComponents();
        preencherTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTratamento = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDiagnosticoC = new javax.swing.JTextField();
        txtDataFinalTratamentoC = new javax.swing.JFormattedTextField();
        txtDataInicialTratamentoC = new javax.swing.JFormattedTextField();
        txtNomeAnimalTratamentoC = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaDescricaoC = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        txtIdTratamentoC = new javax.swing.JTextField();
        jButtonAlterar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonDeletar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableTratamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableTratamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTratamentoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableTratamento);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 590, 140));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Nome Animal :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Data Inical :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Data Final :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Diagnostico :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Descrição Tratamento: ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        txtDiagnosticoC.setEnabled(false);
        jPanel1.add(txtDiagnosticoC, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 210, -1));

        try {
            txtDataFinalTratamentoC.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataFinalTratamentoC.setEnabled(false);
        jPanel1.add(txtDataFinalTratamentoC, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 80, -1));

        try {
            txtDataInicialTratamentoC.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataInicialTratamentoC.setEnabled(false);
        jPanel1.add(txtDataInicialTratamentoC, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 80, -1));

        txtNomeAnimalTratamentoC.setEnabled(false);
        jPanel1.add(txtNomeAnimalTratamentoC, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 210, -1));

        jTextAreaDescricaoC.setColumns(20);
        jTextAreaDescricaoC.setRows(5);
        jTextAreaDescricaoC.setEnabled(false);
        jScrollPane2.setViewportView(jTextAreaDescricaoC);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 210, 90));

        jLabel7.setText("ID :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        txtIdTratamentoC.setEnabled(false);
        jPanel1.add(txtIdTratamentoC, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 50, -1));

        jButtonAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/gui/icones/reload.png"))); // NOI18N
        jButtonAlterar.setText("Alterar");
        jButtonAlterar.setEnabled(false);
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, 100, 33));

        jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/gui/icones/excluir.png"))); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setEnabled(false);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, 100, 33));

        jButtonSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/gui/icones/salvar_1.png"))); // NOI18N
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, 100, 33));

        jButtonDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/gui/icones/trash.gif"))); // NOI18N
        jButtonDeletar.setText("Deletar");
        jButtonDeletar.setEnabled(false);
        jButtonDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeletarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonDeletar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, 100, 33));

        jPanel2.setBackground(new java.awt.Color(0, 102, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Consultar Tratamento");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(228, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(231, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        habilitarCampos();
        jButtonSalvar.setEnabled(true);
        jButtonAlterar.setEnabled(false);
        jButtonCancelar.setEnabled(true);
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        limparCampos();

        jButtonAlterar.setEnabled(false);
        jButtonDeletar.setEnabled(false);
        jButtonCancelar.setEnabled(false);
        jButtonSalvar.setEnabled(false);

        desabilitarCampos();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed

        Tratamento t = new Tratamento();
        FachadaTratamento ft = new FachadaTratamento();
        t.setCodigoTratamento(Integer.parseInt(txtIdTratamentoC.getText()));
        t.setNomeAnimal(txtNomeAnimalTratamentoC.getText());
        t.setDescricaoTratamento(jTextAreaDescricaoC.getText());
        t.setDataFinalTratamento(txtDataFinalTratamentoC.getText());
        t.setDataInicialTratamento(txtDataInicialTratamentoC.getText());
        t.setDiagnosticoTratamento(txtDiagnosticoC.getText());

        try{

            ft.alterarTratamento(t);
            limparCampos();

        }catch(RegraExceptionTratamento ex ){
            Msg.msgErro("Não foi possivel alterar o tratamento", "Erro ao alterar Tratamento");
        }catch(ConexaoException ex){
            Msg.msgErro("Não foi possivel alterar o tratamento", "Erro de conexão");
        }catch(DaoException ex){
            Msg.msgErro("Não foi possivel alterar o tratamento", "Erro de SQL");
        }

        jButtonAlterar.setEnabled(false);
        jButtonDeletar.setEnabled(false);
        jButtonCancelar.setEnabled(false);
        jButtonSalvar.setEnabled(false);

        desabilitarCampos();
        preencherTabela();
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeletarActionPerformed

        FachadaTratamento f = new FachadaTratamento();
        try {
            f.deletarTratamento(Integer.parseInt(txtIdTratamentoC.getText()));
        }catch(RegraExceptionTratamento ex ){
            Msg.msgErro("Não foi possivel deletar o tratamento", "Erro ao deletar Tratamento");
        }catch(ConexaoException ex){
            Msg.msgErro("Não foi possivel deletar o tratamento", "Erro de conexão");
        }catch(DaoException ex){
            Msg.msgErro("Não foi possivel deletar o tratamento", "Erro de SQL");
        }

        desabilitarCampos();
        limparCampos();

        jButtonAlterar.setEnabled(false);
        jButtonDeletar.setEnabled(false);
        jButtonCancelar.setEnabled(false);
        jButtonSalvar.setEnabled(false);

        preencherTabela();

    }//GEN-LAST:event_jButtonDeletarActionPerformed

    private void jTableTratamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTratamentoMouseClicked
        int codigoTratamento = Integer.parseInt(String.valueOf(jTableTratamento.getValueAt(jTableTratamento.getSelectedRow(), 0)));
        
        FachadaTratamento ft = new FachadaTratamento();
        try {
            Tratamento t = ft.consultarTratamento(codigoTratamento);
            
            txtIdTratamentoC.setText(String.valueOf(t.getCodigoTratamento()));
            txtNomeAnimalTratamentoC.setText(t.getNomeAnimal());
            txtDataInicialTratamentoC.setText(t.getDataInicialTratamento());
            txtDataFinalTratamentoC.setText(t.getDataFinalTratamento());
            txtDiagnosticoC.setText(t.getDiagnosticoTratamento());
            jTextAreaDescricaoC.setText(t.getDescricaoTratamento());
            
            jButtonAlterar.setEnabled(true);
            jButtonDeletar.setEnabled(true);
            
        } catch (RegraExceptionTratamento ex) {
            Msg.msgErro("Erro ao tentar pegar Tratamento", "Error");
        } catch (ConexaoException ex) {
            Msg.msgErro("Erro ao tentar pegar Tratamento", "Erro de conexao");
        } catch (DaoException ex) {
            Msg.msgErro("Erro ao tentar pegar Tratamento", "Erro de SQL");
        }
    }//GEN-LAST:event_jTableTratamentoMouseClicked

    public void desabilitarCampos(){
        txtNomeAnimalTratamentoC.setEnabled(false);
        txtDataFinalTratamentoC.setEnabled(false);
        txtDataInicialTratamentoC.setEnabled(false);
        txtDiagnosticoC.setEnabled(false);
        jTextAreaDescricaoC.setEnabled(false);
    }
    
    public void habilitarCampos(){
        txtNomeAnimalTratamentoC.setEnabled(true);
        txtDataFinalTratamentoC.setEnabled(true);
        txtDataInicialTratamentoC.setEnabled(true);
        txtDiagnosticoC.setEnabled(true);
        jTextAreaDescricaoC.setEnabled(true);
    }
    
    public void limparCampos(){
        txtIdTratamentoC.setText("");
        txtNomeAnimalTratamentoC.setText("");
        txtDataFinalTratamentoC.setText("");
        txtDataInicialTratamentoC.setText("");
        txtDiagnosticoC.setText("");
        jTextAreaDescricaoC.setText("");
    }
    /**
     * Metodo para popular a tabela
     */
    public void preencherTabela(){
        FachadaTratamento fachadaT = new FachadaTratamento();
        List<Tratamento> listaT = new ArrayList<Tratamento>();
        ArrayList data = new ArrayList();
        String [] colunas = new String []{"Id", "Nome Animal", "Diagnostico", "Descricao", "Data inicio", "Data Fim"};
        try {
            listaT = fachadaT.listarTratamento();
            for(Tratamento lT : listaT){
                data.add(new Object[]{lT.getCodigoTratamento(),lT.getNomeAnimal(),lT.getDiagnosticoTratamento(),lT.getDescricaoTratamento(), lT.getDataInicialTratamento(), lT.getDataFinalTratamento()});
            }
        } catch (RegraExceptionTratamento | ConexaoException | DaoException ex) {
            Msg.msgErro("Não foi possivel carregar os dados de tratamentos", "Erro ao carregar tratamentos");
        }
        
        TableTratamento tabela = new TableTratamento(data, colunas);
        jTableTratamento.setModel(tabela);
        jTableTratamento.getColumnModel().getColumn(0).setPreferredWidth(40);
        jTableTratamento.getColumnModel().getColumn(0).setResizable(false);
        jTableTratamento.getColumnModel().getColumn(1).setPreferredWidth(160);
        jTableTratamento.getColumnModel().getColumn(1).setResizable(false);
        jTableTratamento.getColumnModel().getColumn(2).setPreferredWidth(120);
        jTableTratamento.getColumnModel().getColumn(2).setResizable(false);
        jTableTratamento.getColumnModel().getColumn(3).setPreferredWidth(160);
        jTableTratamento.getColumnModel().getColumn(3).setResizable(false);
        jTableTratamento.getColumnModel().getColumn(4).setPreferredWidth(80);
        jTableTratamento.getColumnModel().getColumn(4).setResizable(false);
        jTableTratamento.getColumnModel().getColumn(5).setPreferredWidth(80);
        jTableTratamento.getColumnModel().getColumn(5).setResizable(false);
        jTableTratamento.getTableHeader().setReorderingAllowed(false);
        jTableTratamento.setAutoResizeMode(jTableTratamento.AUTO_RESIZE_OFF);
        jTableTratamento.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaTratamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaTratamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaTratamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaTratamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaConsultaTratamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonDeletar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableTratamento;
    private javax.swing.JTextArea jTextAreaDescricaoC;
    private javax.swing.JFormattedTextField txtDataFinalTratamentoC;
    private javax.swing.JFormattedTextField txtDataInicialTratamentoC;
    private javax.swing.JTextField txtDiagnosticoC;
    private javax.swing.JTextField txtIdTratamentoC;
    private javax.swing.JTextField txtNomeAnimalTratamentoC;
    // End of variables declaration//GEN-END:variables
}
