/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto.gui.telas;

/**
 *
 * @author daien
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     * @param cpf
     */
    public TelaPrincipal(String cpf) {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        if(cpf.equals("66666666666")){
            jControleFuncionario.setEnabled(true);
        }
    }

    private TelaPrincipal() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBarNavPrincipal = new javax.swing.JMenuBar();
        jMenuArquivo = new javax.swing.JMenu();
        jMenuCliente = new javax.swing.JMenu();
        jMenuItemCadCliente = new javax.swing.JMenuItem();
        jMenuItemConCliente = new javax.swing.JMenuItem();
        JMenuAnimal = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuConsulta = new javax.swing.JMenu();
        jMenuItemAgendarConsulta = new javax.swing.JMenuItem();
        jMenuItemListarConsultas = new javax.swing.JMenuItem();
        jMenuExame = new javax.swing.JMenu();
        jMenuItemMarcarExame = new javax.swing.JMenuItem();
        jMenuItemConsultarExames = new javax.swing.JMenuItem();
        jMenuTratamento = new javax.swing.JMenu();
        jMenuItemAgendarTratamento = new javax.swing.JMenuItem();
        jMenuItemConsultarTratamento = new javax.swing.JMenuItem();
        jControleFuncionario = new javax.swing.JMenuItem();
        jMenuRelatorios = new javax.swing.JMenu();
        jMenuItemRelatConsultas = new javax.swing.JMenuItem();
        jMenuItemRelatExames = new javax.swing.JMenuItem();
        jMenuFerramentas = new javax.swing.JMenu();
        jMenuItemSobre = new javax.swing.JMenuItem();
        jLogOut = new javax.swing.JMenu();
        deslogar = new javax.swing.JMenuItem();
        sair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Principal");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jDesktopPane1.setBackground(new java.awt.Color(204, 204, 255));
        jDesktopPane1.setForeground(new java.awt.Color(255, 255, 255));
        jDesktopPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/gui/icones/logo.png"))); // NOI18N

        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(815, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(82, 82, 82))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(413, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(42, 42, 42))
        );

        jMenuArquivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/gui/icones/user.png"))); // NOI18N
        jMenuArquivo.setText("Arquivo");

        jMenuCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/gui/icones/group.png"))); // NOI18N
        jMenuCliente.setText("Cliente");

        jMenuItemCadCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/gui/icones/add.png"))); // NOI18N
        jMenuItemCadCliente.setText("Cadastrar");
        jMenuItemCadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadClienteActionPerformed(evt);
            }
        });
        jMenuCliente.add(jMenuItemCadCliente);

        jMenuItemConCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/gui/icones/zoom.png"))); // NOI18N
        jMenuItemConCliente.setText("Consultar Clientes");
        jMenuItemConCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConClienteActionPerformed(evt);
            }
        });
        jMenuCliente.add(jMenuItemConCliente);

        jMenuArquivo.add(jMenuCliente);

        JMenuAnimal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/gui/icones/animal.png"))); // NOI18N
        JMenuAnimal.setText("Animal");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/gui/icones/add.png"))); // NOI18N
        jMenuItem1.setText("Cadastrar Animal");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        JMenuAnimal.add(jMenuItem1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/gui/icones/zoom.png"))); // NOI18N
        jMenuItem2.setText("Consultar Animal");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        JMenuAnimal.add(jMenuItem2);

        jMenuArquivo.add(JMenuAnimal);

        jMenuConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/gui/icones/folder.gif"))); // NOI18N
        jMenuConsulta.setText("Consulta");

        jMenuItemAgendarConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/gui/icones/agenda2.png"))); // NOI18N
        jMenuItemAgendarConsulta.setText("Agendar Consulta");
        jMenuItemAgendarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAgendarConsultaActionPerformed(evt);
            }
        });
        jMenuConsulta.add(jMenuItemAgendarConsulta);

        jMenuItemListarConsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/gui/icones/zoom.png"))); // NOI18N
        jMenuItemListarConsultas.setText("Verificar Consultas");
        jMenuItemListarConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListarConsultasActionPerformed(evt);
            }
        });
        jMenuConsulta.add(jMenuItemListarConsultas);

        jMenuArquivo.add(jMenuConsulta);

        jMenuExame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/gui/icones/estetoscopio.png"))); // NOI18N
        jMenuExame.setText("Exame");

        jMenuItemMarcarExame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/gui/icones/agenda2.png"))); // NOI18N
        jMenuItemMarcarExame.setText("Agendar Exame");
        jMenuItemMarcarExame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMarcarExameActionPerformed(evt);
            }
        });
        jMenuExame.add(jMenuItemMarcarExame);

        jMenuItemConsultarExames.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/gui/icones/zoom.png"))); // NOI18N
        jMenuItemConsultarExames.setText("Consultar Exames");
        jMenuItemConsultarExames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultarExamesActionPerformed(evt);
            }
        });
        jMenuExame.add(jMenuItemConsultarExames);

        jMenuArquivo.add(jMenuExame);

        jMenuTratamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/gui/icones/seringa.png"))); // NOI18N
        jMenuTratamento.setText("Tratamento");

        jMenuItemAgendarTratamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/gui/icones/agenda2.png"))); // NOI18N
        jMenuItemAgendarTratamento.setText("Agendar Tratamento");
        jMenuItemAgendarTratamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAgendarTratamentoActionPerformed(evt);
            }
        });
        jMenuTratamento.add(jMenuItemAgendarTratamento);

        jMenuItemConsultarTratamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/gui/icones/zoom.png"))); // NOI18N
        jMenuItemConsultarTratamento.setText("Consultar Tratamento");
        jMenuItemConsultarTratamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultarTratamentoActionPerformed(evt);
            }
        });
        jMenuTratamento.add(jMenuItemConsultarTratamento);

        jMenuArquivo.add(jMenuTratamento);

        jControleFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/gui/icones/func.png"))); // NOI18N
        jControleFuncionario.setText("Controle Funcionario");
        jControleFuncionario.setEnabled(false);
        jControleFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jControleFuncionarioActionPerformed(evt);
            }
        });
        jMenuArquivo.add(jControleFuncionario);

        jMenuBarNavPrincipal.add(jMenuArquivo);

        jMenuRelatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/gui/icones/Relatorios.png"))); // NOI18N
        jMenuRelatorios.setText("Relatórios");

        jMenuItemRelatConsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/gui/icones/relatorios2.png"))); // NOI18N
        jMenuItemRelatConsultas.setText("Relatorio de consultas");
        jMenuRelatorios.add(jMenuItemRelatConsultas);

        jMenuItemRelatExames.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/gui/icones/relatorios2.png"))); // NOI18N
        jMenuItemRelatExames.setText("Relatorio de exames");
        jMenuRelatorios.add(jMenuItemRelatExames);

        jMenuBarNavPrincipal.add(jMenuRelatorios);

        jMenuFerramentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/gui/icones/configs.gif"))); // NOI18N
        jMenuFerramentas.setText("Ferramentas");

        jMenuItemSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/gui/icones/info.png"))); // NOI18N
        jMenuItemSobre.setText("Sobre");
        jMenuItemSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSobreActionPerformed(evt);
            }
        });
        jMenuFerramentas.add(jMenuItemSobre);

        jMenuBarNavPrincipal.add(jMenuFerramentas);

        jLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/gui/icones/Log out.png"))); // NOI18N
        jLogOut.setText("Log Out");

        deslogar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/gui/icones/deslogar.png"))); // NOI18N
        deslogar.setText("Deslogar");
        deslogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deslogarActionPerformed(evt);
            }
        });
        jLogOut.add(deslogar);

        sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/gui/icones/logout.png"))); // NOI18N
        sair.setText("Sair");
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });
        jLogOut.add(sair);

        jMenuBarNavPrincipal.add(jLogOut);

        setJMenuBar(jMenuBarNavPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1093, 681));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadClienteActionPerformed
        new TelaCliente().setVisible(true);
    }//GEN-LAST:event_jMenuItemCadClienteActionPerformed

    private void jMenuItemAgendarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAgendarConsultaActionPerformed
        // TODO add your handling code here:
        new TelaConsulta().setVisible(true);
    }//GEN-LAST:event_jMenuItemAgendarConsultaActionPerformed

    private void jMenuItemMarcarExameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMarcarExameActionPerformed
        // TODO add your handling code here:
        new TelaExame().setVisible(true);
    }//GEN-LAST:event_jMenuItemMarcarExameActionPerformed

    private void jMenuItemAgendarTratamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAgendarTratamentoActionPerformed
        // TODO add your handling code here:
        new TelaTratamento().setVisible(true);
    }//GEN-LAST:event_jMenuItemAgendarTratamentoActionPerformed

    private void jMenuItemSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSobreActionPerformed
        new TelaSobre().setVisible(true);
    }//GEN-LAST:event_jMenuItemSobreActionPerformed

    private void jMenuItemConClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConClienteActionPerformed
        new TelaConsultaCliente().setVisible(true);
    }//GEN-LAST:event_jMenuItemConClienteActionPerformed

    private void jMenuItemConsultarExamesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultarExamesActionPerformed
        new TelaConsultaExame().setVisible(true);
    }//GEN-LAST:event_jMenuItemConsultarExamesActionPerformed

    private void jMenuItemConsultarTratamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultarTratamentoActionPerformed
        new TelaConsultaTratamento().setVisible(true);
    }//GEN-LAST:event_jMenuItemConsultarTratamentoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new TelaAnimal().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        new TelaConsultaAnimal().setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItemListarConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListarConsultasActionPerformed
        new TelaListarConsultas().setVisible(true);
    }//GEN-LAST:event_jMenuItemListarConsultasActionPerformed

    private void jControleFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jControleFuncionarioActionPerformed
        new TelaFuncionario().setVisible(true);
    }//GEN-LAST:event_jControleFuncionarioActionPerformed

    private void deslogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deslogarActionPerformed
        new TelaLogin().setVisible(true);
        dispose();
    }//GEN-LAST:event_deslogarActionPerformed

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_sairActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                TelaPrincipal telaPrincipal = new TelaPrincipal();
                telaPrincipal.setVisible(true);
                telaPrincipal.setExtendedState(MAXIMIZED_BOTH);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu JMenuAnimal;
    private javax.swing.JMenuItem deslogar;
    private javax.swing.JMenuItem jControleFuncionario;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jLogOut;
    private javax.swing.JMenu jMenuArquivo;
    private javax.swing.JMenuBar jMenuBarNavPrincipal;
    private javax.swing.JMenu jMenuCliente;
    private javax.swing.JMenu jMenuConsulta;
    private javax.swing.JMenu jMenuExame;
    private javax.swing.JMenu jMenuFerramentas;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItemAgendarConsulta;
    private javax.swing.JMenuItem jMenuItemAgendarTratamento;
    private javax.swing.JMenuItem jMenuItemCadCliente;
    private javax.swing.JMenuItem jMenuItemConCliente;
    private javax.swing.JMenuItem jMenuItemConsultarExames;
    private javax.swing.JMenuItem jMenuItemConsultarTratamento;
    private javax.swing.JMenuItem jMenuItemListarConsultas;
    private javax.swing.JMenuItem jMenuItemMarcarExame;
    private javax.swing.JMenuItem jMenuItemRelatConsultas;
    private javax.swing.JMenuItem jMenuItemRelatExames;
    private javax.swing.JMenuItem jMenuItemSobre;
    private javax.swing.JMenu jMenuRelatorios;
    private javax.swing.JMenu jMenuTratamento;
    private javax.swing.JMenuItem sair;
    // End of variables declaration//GEN-END:variables
}
