/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto.gui.telas;

import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ListSelectionModel;
import projeto.erro.ConexaoException;
import projeto.erro.DaoException;
import projeto.erro.RegraExceptionAnimal;
import projeto.erro.RegraExceptionCliente;
import projeto.negocio.classesBasicas.Animal;
import projeto.negocio.fachada.FachadaAnimal;
import projeto.util.Msg;
import projeto.util.TableAnimal;

/**
 *
 * @author Mario
 */
public class TelaConsultaAnimal extends javax.swing.JFrame {

    /**
     * Creates new form TelaConsultarFuncionario
     */
    public TelaConsultaAnimal() {
        initComponents();
        preencherTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAnimal = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtNomeAnimal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCpfClienteAnimal = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        txtEspecie = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cbSexoCadastroAnimal = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtDataNascimentoAnimal = new javax.swing.JFormattedTextField();
        jButtonAlterar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonDeletar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtIdAnimal = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTableAnimal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableAnimal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableAnimalMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableAnimal);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Nome Do Animal :");

        txtNomeAnimal.setEnabled(false);
        txtNomeAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeAnimalActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("CPF do Cliente (dono) :");

        try {
            txtCpfClienteAnimal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpfClienteAnimal.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Espécie :");

        txtEspecie.setEnabled(false);
        txtEspecie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEspecieActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Sexo :");

        cbSexoCadastroAnimal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbSexoCadastroAnimal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Macho", "Fêmea" }));
        cbSexoCadastroAnimal.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Data de Nascimento :");

        try {
            txtDataNascimentoAnimal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataNascimentoAnimal.setEnabled(false);

        jButtonAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/gui/icones/reload.png"))); // NOI18N
        jButtonAlterar.setText("Alterar");
        jButtonAlterar.setEnabled(false);
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/gui/icones/excluir.png"))); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setEnabled(false);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/gui/icones/salvar_1.png"))); // NOI18N
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/gui/icones/trash.gif"))); // NOI18N
        jButtonDeletar.setText("Deletar");
        jButtonDeletar.setEnabled(false);
        jButtonDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeletarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("ID :");

        txtIdAnimal.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(120, 120, 120)
                        .addComponent(txtIdAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(42, 42, 42)
                        .addComponent(txtNomeAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jButtonAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(11, 11, 11)
                        .addComponent(txtCpfClienteAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(140, 140, 140)
                        .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(91, 91, 91)
                        .addComponent(txtEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110)
                        .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(105, 105, 105)
                        .addComponent(cbSexoCadastroAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(150, 150, 150)
                        .addComponent(jButtonDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(22, 22, 22)
                        .addComponent(txtDataNascimentoAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtIdAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAlterar)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtNomeAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCancelar)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txtCpfClienteAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonSalvar)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txtEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonDeletar)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(cbSexoCadastroAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txtDataNascimentoAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 102, 204));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Controle Animal");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeAnimalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeAnimalActionPerformed

    private void txtEspecieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEspecieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEspecieActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        
        habilitarCampos();
        
        jButtonSalvar.setEnabled(true);
        jButtonAlterar.setEnabled(false);
        jButtonCancelar.setEnabled(true);
        
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jTableAnimalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableAnimalMouseClicked
        int codigo = Integer.parseInt(String.valueOf(jTableAnimal.getValueAt(jTableAnimal.getSelectedRow(), 0)));
        
        FachadaAnimal f = new FachadaAnimal();
        try {
            Animal a = f.consultarAnimal(codigo);
            
            txtIdAnimal.setText(String.valueOf(a.getCodigoAnimal()));
            txtNomeAnimal.setText(a.getNome());
            txtEspecie.setText(a.getEspecie());
            txtDataNascimentoAnimal.setText(a.getDataNascimento());
            txtCpfClienteAnimal.setText(a.getCpfCliente());
            
            jButtonAlterar.setEnabled(true);
            jButtonDeletar.setEnabled(true);
            
        } catch (RegraExceptionAnimal ex) {
            Msg.msgErro("Erro ao tentar pegar Animal", "Error");
        } catch (ConexaoException ex) {
            Msg.msgErro("Erro ao tentar pegar Animal", "Erro de conexao");
        } catch (DaoException ex) {
            Msg.msgErro("Erro ao tentar pegar Animal", "Erro de SQL");
        }
                   
    }//GEN-LAST:event_jTableAnimalMouseClicked

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        
        limparCampos();
        desabilitarCampos();
        jButtonAlterar.setEnabled(false);
        jButtonDeletar.setEnabled(false);
        jButtonCancelar.setEnabled(false);
        jButtonSalvar.setEnabled(false);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        String cpfConverte = txtCpfClienteAnimal.getText().replaceAll("[^0-9]", "");
        String sexo = cbSexoCadastroAnimal.getItemAt(WIDTH).equals("Macho")? "M":"F";

        Animal a = new Animal();
        FachadaAnimal f = new FachadaAnimal();
        a.setCodigoAnimal(Integer.parseInt(txtIdAnimal.getText()));
        a.setNome(txtNomeAnimal.getText());
        a.setEspecie(txtEspecie.getText());
        a.setCpfCliente(cpfConverte);
        a.setDataNascimento(txtDataNascimentoAnimal.getText());
        a.setSexo(sexo);

        try{
            
            f.alterarAnimal(a);
            limparCampos();

        }catch(RegraExceptionAnimal ex ){
            Msg.msgErro("Não foi possivel alterar o animal", "Erro ao alterar animal");
        }catch(ConexaoException ex){
            Msg.msgErro("Não foi possivel alterar o animal", "Erro de Conexão");
        }catch(DaoException ex){
            Msg.msgErro("Não foi possivel alterar o animal", "Erro de SQL");
        } catch (RegraExceptionCliente ex) {
            Msg.msgErro("Não foi possivel vincular este animal a um cliente no Banco de dados","Erro Inesperado");
        }

        jButtonAlterar.setEnabled(false);
        jButtonDeletar.setEnabled(false);
        jButtonCancelar.setEnabled(false);
        jButtonSalvar.setEnabled(false);
        
        desabilitarCampos();
                
        preencherTabela();

    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeletarActionPerformed
        FachadaAnimal f = new FachadaAnimal();
        try {
            f.deletarAnimal(Integer.parseInt(txtIdAnimal.getText()));
        }catch(RegraExceptionAnimal ex ){
            Msg.msgErro("Não foi possivel alterar o animal", "Erro ao alterar animal");
        }catch(ConexaoException ex){
            Msg.msgErro("Não foi possivel alterar o animal", "Erro de Conexão");
        }catch(DaoException ex){
            Msg.msgErro("Não foi possivel alterar o animal", "Erro de SQL");
        }

        desabilitarCampos();
        limparCampos();

        jButtonAlterar.setEnabled(false);
        jButtonDeletar.setEnabled(false);
        jButtonCancelar.setEnabled(false);
        jButtonSalvar.setEnabled(false);
        
        preencherTabela();
    }//GEN-LAST:event_jButtonDeletarActionPerformed

    public void preencherTabela(){
        
        FachadaAnimal fachadaAnimal = new FachadaAnimal();
        List<Animal> listaAnimal = new ArrayList<Animal>();
        ArrayList data = new ArrayList();
        String [] colunas = new String []{"Id", "Nome", "Especie", "Sexo", "Data Nascimento","CPF Dono"};
        try {
            listaAnimal = fachadaAnimal.listarAnimal();
            for(Animal lAnimal : listaAnimal){
                data.add(new Object[]{lAnimal.getCodigoAnimal(),lAnimal.getNome(),lAnimal.getEspecie(),lAnimal.getSexo(),lAnimal.getDataNascimento(),lAnimal.getCpfCliente()});
            }
        } catch (RegraExceptionAnimal | ConexaoException | DaoException ex) {
            Msg.msgErro(ex.getMessage(),"Erro ao listar os animais");
        }
        
        TableAnimal tabela = new TableAnimal(data, colunas);
        jTableAnimal.setModel(tabela);
        jTableAnimal.getColumnModel().getColumn(0).setPreferredWidth(50);
        jTableAnimal.getColumnModel().getColumn(0).setResizable(false);
        jTableAnimal.getColumnModel().getColumn(1).setPreferredWidth(160);
        jTableAnimal.getColumnModel().getColumn(1).setResizable(false);
        jTableAnimal.getColumnModel().getColumn(2).setPreferredWidth(110);
        jTableAnimal.getColumnModel().getColumn(2).setResizable(false);
        jTableAnimal.getColumnModel().getColumn(3).setPreferredWidth(80);
        jTableAnimal.getColumnModel().getColumn(3).setResizable(false);
        jTableAnimal.getColumnModel().getColumn(4).setPreferredWidth(100);
        jTableAnimal.getColumnModel().getColumn(4).setResizable(false);
        jTableAnimal.getColumnModel().getColumn(5).setPreferredWidth(100);
        jTableAnimal.getColumnModel().getColumn(5).setResizable(false);
        jTableAnimal.getTableHeader().setReorderingAllowed(false);
        jTableAnimal.setAutoResizeMode(jTableAnimal.AUTO_RESIZE_OFF);
        jTableAnimal.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
    }
    
    public void limparCampos(){
        txtCpfClienteAnimal.setText("");
        txtDataNascimentoAnimal.setText("");
        txtEspecie.setText("");
        txtNomeAnimal.setText("");
        txtIdAnimal.setText("");
        cbSexoCadastroAnimal.setSelectedItem("Selecione");
    }
    
    public void habilitarCampos(){
        txtCpfClienteAnimal.setEnabled(true);
        txtDataNascimentoAnimal.setEnabled(true);
        txtEspecie.setEnabled(true);
        txtNomeAnimal.setEnabled(true);
        cbSexoCadastroAnimal.setEnabled(true);
    }
    
    public void desabilitarCampos(){
        txtCpfClienteAnimal.setEnabled(false);
        txtDataNascimentoAnimal.setEnabled(false);
        txtEspecie.setEnabled(false);
        txtNomeAnimal.setEnabled(false);
        txtIdAnimal.setEnabled(false);
        cbSexoCadastroAnimal.setEnabled(false);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaConsultaAnimal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbSexoCadastroAnimal;
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonDeletar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAnimal;
    private javax.swing.JFormattedTextField txtCpfClienteAnimal;
    private javax.swing.JFormattedTextField txtDataNascimentoAnimal;
    private javax.swing.JTextField txtEspecie;
    private javax.swing.JTextField txtIdAnimal;
    private javax.swing.JTextField txtNomeAnimal;
    // End of variables declaration//GEN-END:variables
}
